/**
 * List of all the feature toggles
 */
export declare const enum FeatureToggles {
    AGENT_CHAT_FEATURE_TOGGLE = "release-agent-chat-AW-30672",
    AGENT_PROFILE_ADOPTION_FEATURE_TOGGLE = "release-CMA-agent-profile-AW-34218",
    COPILOT_CONFIG_FROM_ACP_BACKEND = "release-agentcopilot-ILLUM-23604",
    COPILOT_EMAIL_CHANNEL_FEATURE_TOGGLE = "release-agentassisthub-ILLUM-11110",
    COPILOT_EMAIL_EXPAND_FEATURE_TOGGLE = "release-agentassisthub-ILLUM-12720",
    COPILOT_JOURNEY_SUMMARY_FEATURE_TOGGLE = "release-agentassisthub-ILLUM-7410",
    COPILOT_TASK_ASSIST_FEATURE_TOGGLE = "release-agentcopilot-taskassist-ILLUM-7077",
    CXA_FAVORITES_FEATURE_TOGGLE = "release-cxa-favorites-AW-40314",
    CXA_LOCATION_SERVICE = "release-cxa-location-service-AW-15862",
    CXA_RECORDING_NOTIFICATION_COMPLIANCE = "release-cxa-recording-compliance-AW-37942",
    DIGITAL_WORKING_STATE_HACK_FEATURE_TOGGLE = "release-cx-agent-state-working-digital-AW-24442",
    EMAIL_RENDERING_FEATURE_TOGGLE = "release-cx-agent-email-rendering-AW-37207",
    GET_ADAPTIVE_CARD_SCHEMAS_FROM_S3 = "release-agentcopilot-schema-versioning-CSA-15839",
    GET_VERSION_FROM_CXSS_VERSIONING_API = "release-cx-agent-cxss-versioning-api-AW-37635",
    INTERACTION_TAB_FEATURE_TOGGLE = "release-cx-agent-interaction-tab-changes-AW-24221",
    INTERACTION_TAB_PINNED_COLUMN = "release-agent-interaction-tab-pinned-column-AW-36969",
    LV_SMARTREACH = "release-tm-customerCard-2.0-crm-11684",
    LV_SMARTREACH_ECC = "release-smartreach-ecc-CXDSK-13",
    LV_SMARTREACH_DESK = "release-smartreach-desk-CXDSK-3",
    NEW_EMAIL_REVAMP_FEATURE_TOGGLE = "release-cx-agent-Revamped_New_Digital_Email_CMA-AW-28772",
    NO_TIMER_FEATURE_TOGGLE = "release-digital-no-timer-AW-36494",
    RESTART_GET_NEXT_EVENT_POLLING_FEATURE_TOGGLE = "release-cxa-get-next-event-restart-AW-37270",
    TOKEN_ENCRYPTION_FEATURE_TOGGLE = "release-cxa-token-update-AW-34038",
    UIQ_INSTANCE_MANAGER_FEATURE_TOGGLE = "release-cxa-uiq-instance-manager-AW-38678",
    USER_SLOT_POLLING_FEATURE_TOGGLE = "release-cx-agent-user-slot-api-aw-24451",
    VOICE_BIO_HUB_FEATURE_TOGGLE = "release-agent-voiceBioHub-AW-24969",
    AUTO_EXPAND_TOGGLE_SETTINGS_FEATURE_TOGGLE = "release-cxa-sf-auto-expand-toggle-settings-CRM-16848",
    NEW_EMAIL_EDITOR_REVAMP_FEATURE_TOGGLE = "release-cx-agent-Revamped_Email_Editor_CMA-AW-28772",
    VOICE_TRANSCRIPT_FEATURE_TOGGLE = "release-agent-voice-transcription-AW-20973",
    SAVE_AND_REDIAL_BUTTON_FEATURE_TOGGLE = "release-cxa-save-and-redial-button-AW-39949",
    DFO_API_FACADE_URL_UPDATE = "release-cxa-dfo-api-facade-url-update-AW-44617",
    DIGITAL_WEBSOCKET_REVAMP_TOGGLE = "release-cx-agent-revamped-eventhub-websocket-AW-44146",
    GET_NEXT_EVENT_POLLING_TIMEOUT_FEATURE_TOGGLE = "release-cxa-get-next-events-timeout-update-AW-45121",
    RELATESTO_MSD_CURRENT_INTERACTION = "release-cxa-RelatesTo-MSD-CRM-10029",
    REVAMPED_WEBSOCKET_INTEGRATION_PATTERN = "release-cx-agent-API-websocket-integration-revamp-AW-42181"
}
