export declare enum VoiceContactStatus {
    RINGING = "ringing",
    INCOMING = "incoming",
    ACTIVE = "active",
    DISCONNECTED = "disconnected",
    HOLD = "hold",
    HOLDING = "holding",
    JOINED = "joined",
    DIALING = "dialing",
    MASKING = "masking",
    INQUEUE = "Inqueue",
    TRANSFER = "transfer",
    CONFERENCE = "conference",
    PREVIEW = "preview",
    CALLBACK = "callback",
    CALL_BACK_DISCONNECTED = "callbackdisconnected",
    NATURAL_CALL_DIALING = "naturalcalldialing",
    NATURAL_CALL_AMD = "naturalcallamd",
    NATURAL_CALL_RINGING = "naturalcallringing"
}
