export declare enum IndexDBKeyNames {
    DIRECTORY_SEARCH_RESPONSE = "searchResponse",
    OB_CHANNEL_LIST = "OBChannels",
    ROUTING_QUEUE = "routingQueue",
    FAV_QUICK_REPLIES = "favouriteQuickReplies",
    FAV_QUICK_REPLIES_OUTBOUND = "favouriteQuickRepliesOutbound",
    AGENT_SETTINGS = "agentSettings",
    ALL_CHANNELS = "allChannels",
    ALL_SKILLS = "allSkills",
    FAVORITE_AGENTS = "favoriteAgents",
    FAVORITE_STANDARD_ADDRESS_BOOK = "favoriteStandardAddressBook",
    COPILOT = "copilot",
    INTERACTION_FAILED_MESSAGES = "interactionFailedMessages",
    WEM_NOTIFICATIONS = "wemNotifications",
    SKILL_ACTIVITY = "SkillActivity",
    ACD_CONTACT_HISTORY = "acdContactHistory",
    FAVORITE_TEAMS = "favoriteTeams",
    FAVORITE_SKILLS = "favoriteSkills",
    FAVORITE_DIGITAL_SKILLS = "favoriteDigitalSkills",
    FAVORITE_EXT_DIR_ENTRIES = "favoriteExtDirectoryEntries",
    CONVERSATIONS_GROUPS = "conversationsGroups",
    VOICE_TRANSCRIPTION = "voiceTranscription",
    OMILIA_GET_NEXT = "omiliaGetNext"
}
