/**
 * Enum for Event Types generated by CXone Digital
 */
export declare enum CXoneDigitalEventType {
    /**
     * Event type for digital case inbox assignee changed.
     */
    CASE_INBOX_ASSIGNEE_CHANGED = "CaseInboxAssigneeChanged",
    /**
     * Event type for digital case status changed.
     */
    CASE_STATUS_CHANGED = "CaseStatusChanged",
    /**
     * Event type for digital message added into case.
     */
    MESSAGE_ADDED_INTO_CASE = "MessageAddedIntoCase",
    /**
     * Event type for digital contact assigned to Agent UI (Not websocket event).
     */
    CASE_INBOX_ASSIGNED = "CaseInboxAssigned",
    /**
     * Event type for digital contact unassigned from Agent UI (Not websocket event).
     */
    CASE_INBOX_UNASSIGNED = "CaseInboxUnassigned"
}
