import { InferType } from 'yup';
export declare const SkillDeliveryParametersYupSchema: import("yup/lib/object").OptionalObjectSchema<{
    complianceRecordsDefaultAccept: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    complianceRecordsDeliveryType: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    complianceRecordsDisabled: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    complianceRecordsTimeout: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    complianceRecordsTimeoutSubsequent: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    confirmationRequiredDefault: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    confirmationRequiredDefaultAccept: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    confirmationRequiredDeliveryType: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    confirmationRequiredDisabled: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    confirmationRequiredTimeout: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    confirmationRequiredTimeoutSubsequent: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    showComplianceButtonDisposition: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showComplianceButtonRequeue: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showComplianceButtonReschedule: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showComplianceButtonSnooze: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonDisposition: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonRequeue: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonReschedule: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonSnooze: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
}, import("yup/lib/object").AnyObject, import("yup/lib/object").TypeOfShape<{
    complianceRecordsDefaultAccept: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    complianceRecordsDeliveryType: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    complianceRecordsDisabled: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    complianceRecordsTimeout: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    complianceRecordsTimeoutSubsequent: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    confirmationRequiredDefault: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    confirmationRequiredDefaultAccept: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    confirmationRequiredDeliveryType: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    confirmationRequiredDisabled: import("yup").BooleanSchema<boolean, import("yup/lib/types").AnyObject, boolean>;
    confirmationRequiredTimeout: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    confirmationRequiredTimeoutSubsequent: import("yup").NumberSchema<number, import("yup/lib/types").AnyObject, number>;
    showComplianceButtonDisposition: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showComplianceButtonRequeue: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showComplianceButtonReschedule: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showComplianceButtonSnooze: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonDisposition: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonRequeue: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonReschedule: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
    showPreviewButtonSnooze: import("yup/lib/boolean").RequiredBooleanSchema<boolean, import("yup/lib/types").AnyObject>;
}>>;
export declare type SkillDeliveryParameters = InferType<typeof SkillDeliveryParametersYupSchema>;
